export function createControlStyles(theme) {
  return {
    infoBox: {
      backgroundColor: theme.card,
      borderColor: theme.border,
      borderRadius: 8,
      borderWidth: 1,
      flex: 1,
      padding: 16,
    },
    infoValue: {
      color: theme.text,
      fontSize: theme.largeText ? 30 : 26,
      fontWeight: '800',
    },
    infoLabel: {
      color: theme.muted,
      fontSize: theme.fontSize,
      marginTop: 4,
    },
    mainButton: {
      alignItems: 'center',
      backgroundColor: theme.primary,
      borderRadius: 8,
      marginTop: 10,
      padding: 14,
    },
    mainButtonText: {
      color: theme.buttonText,
      fontSize: theme.fontSize,
      fontWeight: '800',
    },
    secondaryButton: {
      alignItems: 'center',
      backgroundColor: theme.card,
      borderColor: theme.primary,
      borderRadius: 8,
      borderWidth: 1,
      marginTop: 10,
      padding: 14,
    },
    secondaryButtonText: {
      color: theme.text,
      fontSize: theme.fontSize,
      fontWeight: '800',
    },
    logoutButton: {
      alignSelf: 'flex-start',
      borderColor: theme.border,
      borderRadius: 8,
      borderWidth: 1,
      marginBottom: 14,
      paddingHorizontal: 14,
      paddingVertical: 10,
    },
    logoutButtonText: {
      color: theme.text,
      fontSize: theme.fontSize,
      fontWeight: '700',
    },
    backButton: {
      alignSelf: 'flex-start',
      borderColor: theme.border,
      borderRadius: 8,
      borderWidth: 1,
      marginBottom: 14,
      paddingHorizontal: 14,
      paddingVertical: 10,
    },
    backButtonText: {
      color: theme.text,
      fontSize: theme.fontSize,
      fontWeight: '700',
    },
    fakeInput: {
      backgroundColor: theme.card,
      borderColor: theme.border,
      borderRadius: 8,
      borderWidth: 1,
      marginTop: 10,
      padding: 14,
    },
    fakeInputText: {
      color: theme.muted,
      fontSize: theme.fontSize,
    },
    option: {
      backgroundColor: theme.card,
      borderColor: theme.border,
      borderRadius: 8,
      borderWidth: 1,
      marginTop: 8,
      padding: 14,
    },
    selectedOption: {
      backgroundColor: theme.primary,
      borderColor: theme.primary,
      borderRadius: 8,
      borderWidth: 1,
      marginTop: 8,
      padding: 14,
    },
    optionText: {
      color: theme.text,
      fontSize: theme.fontSize,
      fontWeight: '600',
    },
    selectedOptionText: {
      color: theme.buttonText,
      fontSize: theme.fontSize,
      fontWeight: '800',
    },
    status: {
      color: theme.primary,
      fontSize: theme.fontSize,
      fontWeight: '800',
      marginTop: 8,
    },
    filterButton: {
      backgroundColor: theme.card,
      borderColor: theme.border,
      borderRadius: 8,
      borderWidth: 1,
      paddingHorizontal: 12,
      paddingVertical: 10,
    },
    filterButtonSelected: {
      backgroundColor: theme.primary,
      borderColor: theme.primary,
      borderRadius: 8,
      borderWidth: 1,
      paddingHorizontal: 12,
      paddingVertical: 10,
    },
    filterButtonText: {
      color: theme.text,
      fontSize: theme.fontSize,
      fontWeight: '700',
    },
    filterButtonTextSelected: {
      color: theme.buttonText,
      fontSize: theme.fontSize,
      fontWeight: '800',
    },
    searchInput: {
      backgroundColor: theme.card,
      borderColor: theme.border,
      borderRadius: 8,
      borderWidth: 1,
      color: theme.text,
      fontSize: theme.fontSize,
      marginBottom: 12,
      padding: 14,
    },
    searchPlaceholder: {
      color: theme.muted,
    },
    cancelButton: {
      borderColor: theme.danger,
      borderRadius: 8,
      borderWidth: 1,
      marginTop: 12,
      padding: 12,
    },
    cancelButtonText: {
      color: theme.danger,
      fontSize: theme.fontSize,
      fontWeight: '800',
      textAlign: 'center',
    },
  };
}
